
CREATE  TABLE IF NOT EXISTS `groups` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(20) NOT NULL ,
   `cname` VARCHAR(20) NOT NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX name (`name` ASC) 
  ) DEFAULT CHARSET=utf8  COLLATE=utf8_general_ci AUTO_INCREMENT=1 ;